-- Initial Postgres schema for the student shop app.
-- Generated from the current SQLite schema in shop.db with Postgres-appropriate types.

create table if not exists public.customers (
  customer_id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  gender text not null,
  birthdate date not null,
  created_at timestamptz not null,
  city text,
  state text,
  zip_code text,
  customer_segment text,
  loyalty_tier text,
  is_active boolean not null default true
);

create table if not exists public.products (
  product_id bigint generated by default as identity primary key,
  sku text not null unique,
  product_name text not null,
  category text not null,
  price numeric(12,2) not null,
  cost numeric(12,2) not null,
  is_active boolean not null default true
);

create table if not exists public.orders (
  order_id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(customer_id) on delete restrict,
  order_datetime timestamptz not null,
  billing_zip text,
  shipping_zip text,
  shipping_state text,
  payment_method text not null,
  device_type text not null,
  ip_country text not null,
  promo_used boolean not null default false,
  promo_code text,
  order_subtotal numeric(12,2) not null,
  shipping_fee numeric(12,2) not null,
  tax_amount numeric(12,2) not null,
  order_total numeric(12,2) not null,
  risk_score numeric(5,2) not null default 0,
  is_fraud boolean not null default false
);

create table if not exists public.order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id) on delete cascade,
  product_id bigint not null references public.products(product_id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null,
  line_total numeric(12,2) not null
);

create table if not exists public.shipments (
  shipment_id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(order_id) on delete cascade,
  ship_datetime timestamptz not null,
  carrier text not null,
  shipping_method text not null,
  distance_band text not null,
  promised_days integer not null,
  actual_days integer not null,
  late_delivery boolean not null default false
);

create table if not exists public.product_reviews (
  review_id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(customer_id) on delete cascade,
  product_id bigint not null references public.products(product_id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  review_datetime timestamptz not null,
  review_text text,
  unique (customer_id, product_id)
);

-- Supporting indexes (mirrors SQLite intent; deduplicated where possible)
create index if not exists idx_orders_customer_id on public.orders(customer_id);
create index if not exists idx_orders_datetime on public.orders(order_datetime);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);
create index if not exists idx_reviews_customer on public.product_reviews(customer_id);
create index if not exists idx_reviews_product on public.product_reviews(product_id);
create index if not exists idx_shipments_late on public.shipments(late_delivery);
